# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4266b92dc09303eec566edcec400664219bdbcb154990bafd6f90b93378686dd545a195b5b132bc63929ada524105156ec756590196e694ecb9b23c57abb69a3

test:
  secret_key_base: 4fb23a603338d13764a674e06a91c784b570093f143c6b441cd34014cd01bb2b3200e23c809d4b793e0529fbfcc44e91fe39deac6ef9b86c5729a98e1d84c68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
